changes in the hadronBlock
MRD2F/cmssw pull request #4
Opened 2019-04-22 12:43 UTC by MRD2F

2019-04-22 12:56 UTC, kandrosov requested changes

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                                                CellGrid& grid, bool is_inner)
should be `const CellGrid& grid`

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        }
these loops are not needed

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        Cell& cell = grid[cellIndex];
how can you have cellIndex outside of the for? it is wrong

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                return inputs.tensor<float,4>()(0,eta_index,phi_index,var_index);
why eta_index and phi_index don't depend on cell?

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(rho) = GetValueNorm(rho, 21.49f, 9.713f);
if there is no charged and no neutral pfCand in the cell, also the global vars shouldn't be filled.

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        const bool valid = n_index_chH != 0;
this is a wrong condition to check the validity

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(pfCand_chHad_rel_pt) = valid ? GetValueNorm(pfCands.at(index_chH).polarP4().pt() / tau.p4().pt(),
to improve the speed, do all set inside `if(valid)`, instead using `?` operator in each line. You already set to zero the default values.

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        inputs.flat<float>().setZero();
does it raise some warnings? in the past, similar call resulted in some warning during the compilation.

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(pfCand_chHad_dxy) = hasTrackDetails ? GetValueNorm(std::abs(pfCands.at(index_chH).dxy()) /
same here: call get inside the `if(hasTrackDetails)`

2019-04-22 12:56 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(pfCand_nHad_dphi) = valid ? GetValueLinear(ROOT::Math::VectorUtil::DeltaPhi(pfCands.at(index_nH).polarP4(), tau.polarP4()),
order of arguments in DeltaPhi looks wrong, it should be consistent with how it is done in the training code.

2019-04-23 08:29 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(pfCand_nHad_dphi) = valid ? GetValueLinear(ROOT::Math::VectorUtil::DeltaPhi(pfCands.at(index_nH).polarP4(), tau.polarP4()),
should be done with the function DeltaPhi defined in https://github.com/kandrosov/TauML/blob/1738f430a4d9ffb28fa06566c6fbd974e596659e/Analysis/source/TrainingTupleProducer.cxx#L161?

2019-04-23 09:01 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(pfCand_nHad_dphi) = valid ? GetValueLinear(ROOT::Math::VectorUtil::DeltaPhi(pfCands.at(index_nH).polarP4(), tau.polarP4()),
you can use `dPhi` method defined in https://github.com/MRD2F/cmssw/blob/92bd59f045e15b1623ae153fade59a528c522f82/RecoTauTag/RecoTau/plugins/DeepTauId.cc#L144 (but need to change the order of arguments inside)

2019-04-23 09:04 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        const bool valid = n_index_chH != 0;
first I think the condition was defined here:  https://github.com/kandrosov/TauML/blob/1738f430a4d9ffb28fa06566c6fbd974e596659e/Analysis/source/TrainingTupleProducer.cxx#L366. :

const auto& index_set = cell[type];
n_total = index_set.size();

In this case, is the size of what? the size of cell[type] it's already and int

2019-04-23 09:33 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        const bool valid = n_index_chH != 0;
now in each cell there is only one candidate, so, should check for the presence of a candidate with the given type.

2019-04-23 12:55 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        inputs.flat<float>().setZero();
No, This part doesn't give any warnings for now

2019-04-23 13:14 UTC, kandrosov requested changes

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +    enum vars {rho = 0, tau_pt, tau_eta, tau_inside_ecal_crack, NumberOfInputs, pfCand_chHad_valid,
`NumberOfInputs` should be the last enum element

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        tensorflow::Tensor inputs(tensorflow::DT_FLOAT, {1, eta_index, phi_index, NumberOfInputs});
should use `grid.nCellsEta` and `grid.nCellsPhi`

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        const int max_eta_index = grid.maxEtaIndex(), max_phi_index = grid.maxPhiIndex();
these two lines must be removed.

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            const CellIndex cellIndex{eta_index, phi_index};
- why do you need `cellIndex` object?
- to get eta,phi index in tensor better to call `grid. getEtaTensorIndex(cell.first)` (similar for phi)

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            auto cell_map = std::get<1>(cell);
- better cell.second
- should be const auto&

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            size_t index_nH = cell_map[CellObjectType::PfCand_neutralHadron];
should check presence first, can't index const map with `[]`

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            if(index_chH != 0 && index_nH != 0){
wrong condition: index = 0 corresponds to a valid cell position. Same below

2019-04-23 13:14 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                // get(pfCand_chHad_leadChargedHadrCand) = GetValue(dynamic_cast<const pat::PackedCandidate*>(tau.leadChargedHadrCand().get()));
here should check if a pointer to the current candidate equals to the pointer to leadChargedHadrCand. Similar to what is done here: https://github.com/kandrosov/TauML/blob/v2/Production/src/TauJet.cc#L145-L149

2019-04-23 14:52 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            if(index_chH != 0 && index_nH != 0){
what should be the condition? the same to check presence first, something like: 
`cell_map.count(CellObjectType::PfCand_chargedHadron)`

2019-04-23 14:52 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            size_t index_nH = cell_map[CellObjectType::PfCand_neutralHadron];
you mean that should use at()?

2019-04-23 16:41 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            if(index_chH != 0 && index_nH != 0){
yes

2019-04-23 16:41 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            size_t index_nH = cell_map[CellObjectType::PfCand_neutralHadron];
yes

2019-04-23 17:29 UTC, kandrosov requested changes

2019-04-23 17:29 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            if(valid_chH && valid_nH){
it is enough that one of them is valid, so `||`, not `&&`

2019-04-23 17:29 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(tau_inside_ecal_crack) = GetValue(isInEcalCrack(tau.p4().eta()));
use polarP4

2019-04-23 17:29 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_chHad_dphi) = GetValueLinear(dPhi(tau.p4(),pfCands.at(index_chH).polarP4()),
use polarP4 in all 3 cases above.

2019-04-23 19:15 UTC, kandrosov approved these changes

2019-04-23 19:16 UTC, merged