Updates in the electron block
MRD2F/cmssw pull request #5
Opened 2019-04-24 12:59 UTC by MRD2F

2019-04-24 13:21 UTC, kandrosov requested changes

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        } return true;
should return true only when `if` condition is satisfied, otherwise `false`.

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            if(valid_index_pf_ele)
object indices can be created and set inside the ifs below (same comment for hadron block)

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_ele_valid) = index_ele;
index_ele = 0 corresponds to a valid index, should use `valid_index_ele` here

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_ele_pvAssociationQuality) = GetValueLinear(static_cast<float>(pfCands.at(index_pf_ele).pvAssociationQuality()),
why static_cast is needed here and in all places below? Remove all static_casts.

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                const bool hasTrackDetails = pfCands.at(index_pf_ele).hasTrackDetails() == 1;
isn't `hasTrackDetails()` already returns a boolean? if yes, don't need to compare with 1.

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                const bool cc_valid = cc_ele_energy;
should use the result of the `CalculateElectronClusterVars` to determine the validity

2019-04-24 13:21 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                const bool has_closestCtfTrack =  static_cast<float>(closestCtfTrack->normalizedChi2());
has_closestCtfTrack = closestCtfTrack.isNonnull()

2019-04-24 13:53 UTC, MRD2F commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_ele_pvAssociationQuality) = GetValueLinear(static_cast<float>(pfCands.at(index_pf_ele).pvAssociationQuality()),
it gives this error without it:
 

> error: call of overloaded 'isnormal(pat::PackedCandidate::PVAssociationQuality&)' is ambiguous
>          return std::isnormal(value) ? static_cast<float>(value) : 0.f;

2019-04-24 14:16 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_ele_pvAssociationQuality) = GetValueLinear(static_cast<float>(pfCands.at(index_pf_ele).pvAssociationQuality()),
ok, it means that GetValue should be fixed. I suggest using a template specialization for the integral types.

2019-04-25 08:02 UTC, kandrosov requested changes

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                const bool cc_valid = cc_ele_energy && CalculateElectronClusterVars ;
pointer to the method will always be true. use the returned results, i.e.
```c++
float cc_ele_energy, cc_gamma_energy;
int cc_n_gamma;
const bool cc_valid = CalculateElectronClusterVars(electrons.at(index_ele), cc_ele_energy, cc_gamma_energy, cc_n_gamma);
```

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0.1221f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0, 7, true);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0.1226f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0.001f, 1.024f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        3.203f) : 0;
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    true);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    GetValue(pfCands.at(index_pf_gamma).puppiWeightNoLep());
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    GetValue(pfCands.at(index_pf_gamma).lostInnerHits());
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    GetValueLinear(pfCands.at(index_pf_gamma).numberOfPixelHits(), 0, 7, true);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0.0005f, 1.735f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    -0.0008f, 1.752f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                     -0.0201f, 8.333f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        4.774f) : 0;
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        1.729f, 1.644f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    15.13f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    0.0052f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    3.049f, 10.39f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        electrons.at(index_ele).polarP4().pt(), 1.355f, 16.81f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        gsfTrack->ptError(), 5.046f, 3.119f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        GetValueNorm(closestCtfTrack->normalizedChi2(), 2.411f, 6.98f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        15.16f, 5.26f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
>                  const bool hasTrackDetails = pfCands.at(index_chH).hasTrackDetails() == 1;
`hasTrackDetails()` already returns boolean

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    true);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    GetValue(pfCands.at(index_chH).puppiWeightNoLep());
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    1.735f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    1.752f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    8.333f);
don't create a new line

2019-04-25 08:02 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    true);
don't create a new line

2019-04-25 09:15 UTC, kandrosov requested changes

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +    static bool CalculateElectronClusterVars(const pat::Electron& ele, float& cc_ele_energy, float& cc_gamma_energy,
method name should start with a small letter

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        } else return false;
put the return in a new line

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            0, pi, true) : 0;
```c++
get(tau_gj_angle_diff) = tau_gj_angle_diff_valid ?
    GetValueLinear(calculateGottfriedJacksonAngleDifference(tau), 0, pi, true) : 0;
```

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                const bool hasTrackDetails = pfCands.at(index_pf_gamma).hasTrackDetails() == 1;
`hasTrackDetails()` returns a boolean, don't need to compare with 1

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        pfCands.at(index_pf_gamma).pseudoTrack().ndof(), 4.268f, 15.47f) : 0;
```
get(pfCand_gamma_track_chi2_ndof) = pfCands.at(index_pf_gamma).pseudoTrack().ndof() > 0 ?
    GetValueNorm(pfCands.at(index_pf_gamma).pseudoTrack().chi2() /
                 pfCands.at(index_pf_gamma).pseudoTrack().ndof(), 4.268f, 15.47f) : 0;
```

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                        4.774f) : 0;
```c++
get(pfCand_gamma_track_ndof) = pfCands.at(index_pf_gamma).pseudoTrack().ndof() > 0 ?
    GetValueNorm(pfCands.at(index_pf_gamma).pseudoTrack().ndof(), 12.25f, 4.774f) : 0;
```

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    cc_gamma_energy, cc_n_gamma);;
- don't create a new line
- don't put `;` twice
- don't call CalculateElectronClusterVars twice

2019-04-25 09:15 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
>                          pfCands.at(index_chH).pseudoTrack().ndof(), 0.7876f, 3.694f) : 0;
```c++
get(pfCand_chHad_track_chi2_ndof) = pfCands.at(index_chH).pseudoTrack().ndof() > 0 ? 
    GetValueNorm(pfCands.at(index_chH).pseudoTrack().chi2() /
                 pfCands.at(index_chH).pseudoTrack().ndof(), 0.7876f, 3.694f) : 0;
```

2019-04-25 09:16 UTC, kandrosov commented
also fix other method namings, e.g. `GetValue` -> `getValue` etc.

2019-04-26 07:58 UTC, kandrosov requested changes

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +        get(tau_e_ratio) = tau_e_ratio_valid ? getValueLinear(reco::tau::eratio(tau), 0, 1, true) : 0.f;
don't call `reco::tau::eratio(tau)` 3 times. save the result in a local variable and use it.

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            getValueLinear(calculateGottfriedJacksonAngleDifference(tau), 0, pi, true) : 0;
don't call `calculateGottfriedJacksonAngleDifference(tau)` twice. Use `gj_angle_diff` defined above.

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +            size_t index_pf_ele, index_pf_gamma, index_ele;
definition of index_* can be done inside corresponding if

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    is_inner ? 0.9792f : 0.304f, is_inner ? 1.669f : 0.3833f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_gamma_vertex_dx) = getValueNorm(pfCands.at(index_pf_gamma).vertex().x() - pv.position().x(), 0.0005f, 1.735f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_gamma_vertex_dy) = getValueNorm(pfCands.at(index_pf_gamma).vertex().x() - pv.position().y(), -0.0008f, 1.752f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(pfCand_gamma_vertex_dz) = getValueNorm(pfCands.at(index_pf_gamma).vertex().z() - pv.position().z(), -0.0201f, 8.333f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    pv.position().x() - tau.flightLength().x(), -0.0014f, 1.93f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    pv.position().y() - tau.flightLength().y(), 0.0022f, 1.948f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    pv.position().z() - tau.flightLength().z(), -0.0138f, 8.622f);
values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                    getValueNorm(pfCands.at(index_pf_gamma).pseudoTrack().ndof(), 12.25f, 4.774f) : 0;
wrong indention

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                get(ele_eEleClusterOverPout) = getValueNorm(electrons.at(index_ele).eSeedClusterOverPout(), 6.64f, 36.8f);
the values are wrong

2019-04-26 07:58 UTC, kandrosov commented on RecoTauTag/RecoTau/plugins/DeepTauId.cc
> +                index_chH = cell_map.at(CellObjectType::PfCand_chargedHadron);
`index_chH` and `index_nH` can be declared inside the corresponding if, instead of L911.

2019-04-26 12:51 UTC, kandrosov approved these changes

2019-04-26 12:52 UTC, merged